name: Release to GitHub

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Clean up old distribution
      run: bash clean_package.sh

    - name: Determine Package Version
      id: get_version
      run: echo "PKG_VERSION=$(bash get_version.sh)" >> $GITHUB_ENV

    - name: Build distribution
      run: bash build_package.sh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        name: Release ${{ env.PKG_VERSION }} of ${{ github.repository }}
        body: This is the release of ${{ github.repository }} for version ${{ env.PKG_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
